---
###############################################################################
################################# INSTALL #####################################
###############################################################################


# - debug: var=preexisting


- block:
  - name: "add {{ mqtt_group }} system group"
    group:
        name: "{{ mqtt_group }}"
        state: present
        system: true
  - name: "add {{mqtt_user}} service account"
    user:
        name: "{{ mqtt_user }}"
        comment: "Homebridge Service Account"
        group: "{{ mqtt_group }}"
        home: "{{ mqtt_prefix }}"
        shell: /usr/sbin/nologin
        password_lock: true
  become: yes
  become_user: root
  tags: vault_add_user
