---
###############################################################################
################################# INSTALL #####################################
###############################################################################


# - debug: var=preexisting


  - name: Add default config
    template:
      src: config.conf.j2
      dest: "{{mqtt_conf_dir}}/mosquitto.conf"
      mode: 0600
      owner: "{{mqtt_user}}"
      group: "{{mqtt_group}}"
