---





#--name=mqtt  --env-file=envfile -v ./etc-mqtt/:/etc/mqtt/:z -v ./etc-dnsmasq.d/:/etc/dnsmasq.d/:z --network=host mqtt/mqtt:latest

###############################################################################
################################ CONFIGURE ####################################
###############################################################################


- name: Add envfile for {{container_friendly_name}}
  template:
    src: container.envfile.j2
    dest: "{{container_env_file}}"
    mode: 0644
    owner: "{{container_user}}"
    group: "{{container_group}}"
