---
- name: restart mqtt
  become: yes
  become_user: "{{mqtt_user}}"
  service:
    name: mqtt
    state: restarted

- name: reload systemd
  become: yes
  become_user: root
  command: systemctl daemon-reload
